-- ============================================================================
--  Migracion 004 — reglas semilla de los bancos dominicanos
--
--  GENERADO por scripts/generar-seed-reglas.ts — no editar a mano.
--  Regenerar con:  npm run seed:reglas
--
--  AVISO: estos patrones estan escritos a partir de la redaccion HABITUAL de
--  una notificacion bancaria, no de correos reales de cada banco. Trátalos
--  como punto de partida: corre "npm run probar:correo" con un correo de
--  verdad y ajusta el patron que falle. Se corrigen con un UPDATE aqui, sin
--  recompilar ni publicar un APK nuevo.
--
--  Requiere la migracion 003.
-- ============================================================================

insert into reglas_correo
  (id, user_id, banco, remitentes, asunto_contiene, tipo, patron_monto, patron_fecha,
   patron_comercio, patron_tarjeta, patrones_excluir, activa, prioridad)
values
  ('bhd-pago', null, 'BHD', array['bhd.com.do','bhdleon.com.do'], array['pago','abono','deposito','depósito','credito aplicado','pago recibido'], 'pago'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , null, '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 0),
  ('bhd-consumo', null, 'BHD', array['bhd.com.do','bhdleon.com.do'], array['consumo','compra','transaccion','transacción','cargo','debito','débito','retiro','avance'], 'consumo'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , '(?:en|comercio|establecimiento|afiliado)[:\s]+([A-Z0-9][A-Z0-9 ._&''-]{2,40}?)(?:\s+(?:el|por|con|the|la fecha)\b|[,.\n])', '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 1),
  ('banreservas-pago', null, 'Banreservas', array['banreservas.com','banreservas.com.do'], array['pago','abono','deposito','depósito','credito aplicado','pago recibido'], 'pago'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , null, '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 2),
  ('banreservas-consumo', null, 'Banreservas', array['banreservas.com','banreservas.com.do'], array['consumo','compra','transaccion','transacción','cargo','debito','débito','retiro','avance'], 'consumo'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , '(?:en|comercio|establecimiento|afiliado)[:\s]+([A-Z0-9][A-Z0-9 ._&''-]{2,40}?)(?:\s+(?:el|por|con|the|la fecha)\b|[,.\n])', '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 3),
  ('popular-pago', null, 'Popular', array['popularenlinea.com','bpd.com.do'], array['pago','abono','deposito','depósito','credito aplicado','pago recibido'], 'pago'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , null, '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 4),
  ('popular-consumo', null, 'Popular', array['popularenlinea.com','bpd.com.do'], array['consumo','compra','transaccion','transacción','cargo','debito','débito','retiro','avance'], 'consumo'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , '(?:en|comercio|establecimiento|afiliado)[:\s]+([A-Z0-9][A-Z0-9 ._&''-]{2,40}?)(?:\s+(?:el|por|con|the|la fecha)\b|[,.\n])', '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 5),
  ('qik-pago', null, 'Qik', array['qik.com.do','qikbanco.com'], array['pago','abono','deposito','depósito','credito aplicado','pago recibido'], 'pago'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , null, '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 6),
  ('qik-consumo', null, 'Qik', array['qik.com.do','qikbanco.com'], array['consumo','compra','transaccion','transacción','cargo','debito','débito','retiro','avance'], 'consumo'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , '(?:en|comercio|establecimiento|afiliado)[:\s]+([A-Z0-9][A-Z0-9 ._&''-]{2,40}?)(?:\s+(?:el|por|con|the|la fecha)\b|[,.\n])', '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 7),
  ('santa-cruz-pago', null, 'Santa Cruz', array['bancosantacruz.com.do','bsc.com.do'], array['pago','abono','deposito','depósito','credito aplicado','pago recibido'], 'pago'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , null, '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 8),
  ('santa-cruz-consumo', null, 'Santa Cruz', array['bancosantacruz.com.do','bsc.com.do'], array['consumo','compra','transaccion','transacción','cargo','debito','débito','retiro','avance'], 'consumo'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , '(?:en|comercio|establecimiento|afiliado)[:\s]+([A-Z0-9][A-Z0-9 ._&''-]{2,40}?)(?:\s+(?:el|por|con|the|la fecha)\b|[,.\n])', '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 9),
  ('promerica-pago', null, 'Promerica', array['promerica.com.do'], array['pago','abono','deposito','depósito','credito aplicado','pago recibido'], 'pago'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , null, '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 10),
  ('promerica-consumo', null, 'Promerica', array['promerica.com.do'], array['consumo','compra','transaccion','transacción','cargo','debito','débito','retiro','avance'], 'consumo'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , '(?:en|comercio|establecimiento|afiliado)[:\s]+([A-Z0-9][A-Z0-9 ._&''-]{2,40}?)(?:\s+(?:el|por|con|the|la fecha)\b|[,.\n])', '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 11),
  ('scotiabank-pago', null, 'Scotiabank', array['scotiabank.com.do'], array['pago','abono','deposito','depósito','credito aplicado','pago recibido'], 'pago'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , null, '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 12),
  ('scotiabank-consumo', null, 'Scotiabank', array['scotiabank.com.do'], array['consumo','compra','transaccion','transacción','cargo','debito','débito','retiro','avance'], 'consumo'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , '(?:en|comercio|establecimiento|afiliado)[:\s]+([A-Z0-9][A-Z0-9 ._&''-]{2,40}?)(?:\s+(?:el|por|con|the|la fecha)\b|[,.\n])', '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 13),
  ('apap-pago', null, 'APAP', array['apap.com.do'], array['pago','abono','deposito','depósito','credito aplicado','pago recibido'], 'pago'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , null, '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 14),
  ('apap-consumo', null, 'APAP', array['apap.com.do'], array['consumo','compra','transaccion','transacción','cargo','debito','débito','retiro','avance'], 'consumo'::tipo_movimiento_deuda, '(?:RD\$|US\$|DOP|USD|\$)\s*([\d.,]+)', '(\d{1,2}[-/]\d{1,2}[-/]\d{2,4}|\d{4}-\d{2}-\d{2}|\d{1,2}\s+de\s+[a-zA-Záéíóú]+\s+de\s+\d{4})' , '(?:en|comercio|establecimiento|afiliado)[:\s]+([A-Z0-9][A-Z0-9 ._&''-]{2,40}?)(?:\s+(?:el|por|con|the|la fecha)\b|[,.\n])', '(?:termina(?:da|ci[oó]n)?\s*(?:en|:)?|final(?:izada)?\s*(?:en|:)?|\*{2,}|x{2,})\s*(\d{4})', array['declinad','rechazad','no (?:fue |se )?(?:proces|autoriz|complet)','revers','anulad','cancelad','intento (?:de )?(?:compra|transacci)','sospechos','fraude','saldo disponible es','limite de credito es'], true, 15)
on conflict (id) do update set
  remitentes       = excluded.remitentes,
  asunto_contiene  = excluded.asunto_contiene,
  patron_monto     = excluded.patron_monto,
  patron_fecha     = excluded.patron_fecha,
  patron_comercio  = excluded.patron_comercio,
  patron_tarjeta   = excluded.patron_tarjeta,
  patrones_excluir = excluded.patrones_excluir,
  actualizado_en   = now()
-- Solo se pisan las reglas COMUNES: si ya corregiste una regla tuya, se respeta.
where reglas_correo.user_id is null;
